apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-postgres
  template:
    metadata:
      labels:
        app: todo-postgres
    spec:
      containers:
      - name: postgres
        image: archcra/todo-postgres:v6.1
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"
        - name: POSTGRES_DB
          value: "todo"
