apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: todo-app
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: todo-app
  path: ./k8s/overlays/prod
  prune: true
